package org.yaukie.frame.autocode.model;

import java.io.Serializable;

public class XEmailConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.id
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.sender_account
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private String senderAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.sender_authorization_code
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private String senderAuthorizationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.sender_name
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private String senderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.smtp_host
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private String smtpHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.default_port
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private String defaultPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_email_config.ssl_port
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private String sslPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.id
     *
     * @return the value of x_email_config.id
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.id
     *
     * @param id the value for x_email_config.id
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.sender_account
     *
     * @return the value of x_email_config.sender_account
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getSenderAccount() {
        return senderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.sender_account
     *
     * @param senderAccount the value for x_email_config.sender_account
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setSenderAccount(String senderAccount) {
        this.senderAccount = senderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.sender_authorization_code
     *
     * @return the value of x_email_config.sender_authorization_code
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getSenderAuthorizationCode() {
        return senderAuthorizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.sender_authorization_code
     *
     * @param senderAuthorizationCode the value for x_email_config.sender_authorization_code
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setSenderAuthorizationCode(String senderAuthorizationCode) {
        this.senderAuthorizationCode = senderAuthorizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.sender_name
     *
     * @return the value of x_email_config.sender_name
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.sender_name
     *
     * @param senderName the value for x_email_config.sender_name
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.smtp_host
     *
     * @return the value of x_email_config.smtp_host
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getSmtpHost() {
        return smtpHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.smtp_host
     *
     * @param smtpHost the value for x_email_config.smtp_host
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setSmtpHost(String smtpHost) {
        this.smtpHost = smtpHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.default_port
     *
     * @return the value of x_email_config.default_port
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getDefaultPort() {
        return defaultPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.default_port
     *
     * @param defaultPort the value for x_email_config.default_port
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setDefaultPort(String defaultPort) {
        this.defaultPort = defaultPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_email_config.ssl_port
     *
     * @return the value of x_email_config.ssl_port
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getSslPort() {
        return sslPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_email_config.ssl_port
     *
     * @param sslPort the value for x_email_config.ssl_port
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setSslPort(String sslPort) {
        this.sslPort = sslPort;
    }
}