package org.yaukie.frame.autocode.model;

import java.util.ArrayList;
import java.util.List;

public class XEmailConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public XEmailConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSenderAccountIsNull() {
            addCriterion("sender_account is null");
            return (Criteria) this;
        }

        public Criteria andSenderAccountIsNotNull() {
            addCriterion("sender_account is not null");
            return (Criteria) this;
        }

        public Criteria andSenderAccountEqualTo(String value) {
            addCriterion("sender_account =", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotEqualTo(String value) {
            addCriterion("sender_account <>", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountGreaterThan(String value) {
            addCriterion("sender_account >", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountGreaterThanOrEqualTo(String value) {
            addCriterion("sender_account >=", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountLessThan(String value) {
            addCriterion("sender_account <", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountLessThanOrEqualTo(String value) {
            addCriterion("sender_account <=", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountLike(String value) {
            addCriterion("sender_account like", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotLike(String value) {
            addCriterion("sender_account not like", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountIn(List<String> values) {
            addCriterion("sender_account in", values, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotIn(List<String> values) {
            addCriterion("sender_account not in", values, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountBetween(String value1, String value2) {
            addCriterion("sender_account between", value1, value2, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotBetween(String value1, String value2) {
            addCriterion("sender_account not between", value1, value2, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeIsNull() {
            addCriterion("sender_authorization_code is null");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeIsNotNull() {
            addCriterion("sender_authorization_code is not null");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeEqualTo(String value) {
            addCriterion("sender_authorization_code =", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeNotEqualTo(String value) {
            addCriterion("sender_authorization_code <>", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeGreaterThan(String value) {
            addCriterion("sender_authorization_code >", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sender_authorization_code >=", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeLessThan(String value) {
            addCriterion("sender_authorization_code <", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeLessThanOrEqualTo(String value) {
            addCriterion("sender_authorization_code <=", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeLike(String value) {
            addCriterion("sender_authorization_code like", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeNotLike(String value) {
            addCriterion("sender_authorization_code not like", value, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeIn(List<String> values) {
            addCriterion("sender_authorization_code in", values, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeNotIn(List<String> values) {
            addCriterion("sender_authorization_code not in", values, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeBetween(String value1, String value2) {
            addCriterion("sender_authorization_code between", value1, value2, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderAuthorizationCodeNotBetween(String value1, String value2) {
            addCriterion("sender_authorization_code not between", value1, value2, "senderAuthorizationCode");
            return (Criteria) this;
        }

        public Criteria andSenderNameIsNull() {
            addCriterion("sender_name is null");
            return (Criteria) this;
        }

        public Criteria andSenderNameIsNotNull() {
            addCriterion("sender_name is not null");
            return (Criteria) this;
        }

        public Criteria andSenderNameEqualTo(String value) {
            addCriterion("sender_name =", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotEqualTo(String value) {
            addCriterion("sender_name <>", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameGreaterThan(String value) {
            addCriterion("sender_name >", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("sender_name >=", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameLessThan(String value) {
            addCriterion("sender_name <", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameLessThanOrEqualTo(String value) {
            addCriterion("sender_name <=", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameLike(String value) {
            addCriterion("sender_name like", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotLike(String value) {
            addCriterion("sender_name not like", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameIn(List<String> values) {
            addCriterion("sender_name in", values, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotIn(List<String> values) {
            addCriterion("sender_name not in", values, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameBetween(String value1, String value2) {
            addCriterion("sender_name between", value1, value2, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotBetween(String value1, String value2) {
            addCriterion("sender_name not between", value1, value2, "senderName");
            return (Criteria) this;
        }

        public Criteria andSmtpHostIsNull() {
            addCriterion("smtp_host is null");
            return (Criteria) this;
        }

        public Criteria andSmtpHostIsNotNull() {
            addCriterion("smtp_host is not null");
            return (Criteria) this;
        }

        public Criteria andSmtpHostEqualTo(String value) {
            addCriterion("smtp_host =", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotEqualTo(String value) {
            addCriterion("smtp_host <>", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostGreaterThan(String value) {
            addCriterion("smtp_host >", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostGreaterThanOrEqualTo(String value) {
            addCriterion("smtp_host >=", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostLessThan(String value) {
            addCriterion("smtp_host <", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostLessThanOrEqualTo(String value) {
            addCriterion("smtp_host <=", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostLike(String value) {
            addCriterion("smtp_host like", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotLike(String value) {
            addCriterion("smtp_host not like", value, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostIn(List<String> values) {
            addCriterion("smtp_host in", values, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotIn(List<String> values) {
            addCriterion("smtp_host not in", values, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostBetween(String value1, String value2) {
            addCriterion("smtp_host between", value1, value2, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andSmtpHostNotBetween(String value1, String value2) {
            addCriterion("smtp_host not between", value1, value2, "smtpHost");
            return (Criteria) this;
        }

        public Criteria andDefaultPortIsNull() {
            addCriterion("default_port is null");
            return (Criteria) this;
        }

        public Criteria andDefaultPortIsNotNull() {
            addCriterion("default_port is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultPortEqualTo(String value) {
            addCriterion("default_port =", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortNotEqualTo(String value) {
            addCriterion("default_port <>", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortGreaterThan(String value) {
            addCriterion("default_port >", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortGreaterThanOrEqualTo(String value) {
            addCriterion("default_port >=", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortLessThan(String value) {
            addCriterion("default_port <", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortLessThanOrEqualTo(String value) {
            addCriterion("default_port <=", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortLike(String value) {
            addCriterion("default_port like", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortNotLike(String value) {
            addCriterion("default_port not like", value, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortIn(List<String> values) {
            addCriterion("default_port in", values, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortNotIn(List<String> values) {
            addCriterion("default_port not in", values, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortBetween(String value1, String value2) {
            addCriterion("default_port between", value1, value2, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andDefaultPortNotBetween(String value1, String value2) {
            addCriterion("default_port not between", value1, value2, "defaultPort");
            return (Criteria) this;
        }

        public Criteria andSslPortIsNull() {
            addCriterion("ssl_port is null");
            return (Criteria) this;
        }

        public Criteria andSslPortIsNotNull() {
            addCriterion("ssl_port is not null");
            return (Criteria) this;
        }

        public Criteria andSslPortEqualTo(String value) {
            addCriterion("ssl_port =", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortNotEqualTo(String value) {
            addCriterion("ssl_port <>", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortGreaterThan(String value) {
            addCriterion("ssl_port >", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortGreaterThanOrEqualTo(String value) {
            addCriterion("ssl_port >=", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortLessThan(String value) {
            addCriterion("ssl_port <", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortLessThanOrEqualTo(String value) {
            addCriterion("ssl_port <=", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortLike(String value) {
            addCriterion("ssl_port like", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortNotLike(String value) {
            addCriterion("ssl_port not like", value, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortIn(List<String> values) {
            addCriterion("ssl_port in", values, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortNotIn(List<String> values) {
            addCriterion("ssl_port not in", values, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortBetween(String value1, String value2) {
            addCriterion("ssl_port between", value1, value2, "sslPort");
            return (Criteria) this;
        }

        public Criteria andSslPortNotBetween(String value1, String value2) {
            addCriterion("ssl_port not between", value1, value2, "sslPort");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_email_config
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 23 09:51:10 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}