package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.sql.Time;
import java.util.Date;

public class XJobMail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_job_mail.id
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_job_mail.job_id
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_job_mail.begin_time
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    private Time beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_job_mail.end_time
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    private Time endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_job_mail.kjb_path
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
//    private String kjbPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_job_mail.id
     *
     * @return the value of x_job_mail.id
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_job_mail.id
     *
     * @param id the value for x_job_mail.id
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_job_mail.job_id
     *
     * @return the value of x_job_mail.job_id
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_job_mail.job_id
     *
     * @param jobId the value for x_job_mail.job_id
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_job_mail.begin_time
     *
     * @return the value of x_job_mail.begin_time
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_job_mail.begin_time
     *
     * @param beginTime the value for x_job_mail.begin_time
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public void setBeginTime(Time beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_job_mail.end_time
     *
     * @return the value of x_job_mail.end_time
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_job_mail.end_time
     *
     * @param endTime the value for x_job_mail.end_time
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }


}