package org.yaukie.frame.autocode.model;

import java.io.Serializable;
import java.util.Date;

public class XUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.password
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_name
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.nick_name
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.organ_id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String organId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_email
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_phone
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_avater
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String userAvater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.status
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.is_admin
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.create_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.update_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.token
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.lock_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private Date lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.expired_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.id
     *
     * @return the value of x_user.id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.id
     *
     * @param id the value for x_user.id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_id
     *
     * @return the value of x_user.user_id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_id
     *
     * @param userId the value for x_user.user_id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.password
     *
     * @return the value of x_user.password
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.password
     *
     * @param password the value for x_user.password
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_name
     *
     * @return the value of x_user.user_name
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_name
     *
     * @param userName the value for x_user.user_name
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.nick_name
     *
     * @return the value of x_user.nick_name
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.nick_name
     *
     * @param nickName the value for x_user.nick_name
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.organ_id
     *
     * @return the value of x_user.organ_id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getOrganId() {
        return organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.organ_id
     *
     * @param organId the value for x_user.organ_id
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_email
     *
     * @return the value of x_user.user_email
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_email
     *
     * @param userEmail the value for x_user.user_email
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_phone
     *
     * @return the value of x_user.user_phone
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_phone
     *
     * @param userPhone the value for x_user.user_phone
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_avater
     *
     * @return the value of x_user.user_avater
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getUserAvater() {
        return userAvater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_avater
     *
     * @param userAvater the value for x_user.user_avater
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setUserAvater(String userAvater) {
        this.userAvater = userAvater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.status
     *
     * @return the value of x_user.status
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.status
     *
     * @param status the value for x_user.status
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.is_admin
     *
     * @return the value of x_user.is_admin
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.is_admin
     *
     * @param isAdmin the value for x_user.is_admin
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.create_time
     *
     * @return the value of x_user.create_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.create_time
     *
     * @param createTime the value for x_user.create_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.update_time
     *
     * @return the value of x_user.update_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.update_time
     *
     * @param updateTime the value for x_user.update_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.token
     *
     * @return the value of x_user.token
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.token
     *
     * @param token the value for x_user.token
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.lock_time
     *
     * @return the value of x_user.lock_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.lock_time
     *
     * @param lockTime the value for x_user.lock_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.expired_time
     *
     * @return the value of x_user.expired_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.expired_time
     *
     * @param expiredTime the value for x_user.expired_time
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }
}