package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XEmailConfig;
import org.yaukie.frame.autocode.model.XEmailConfigExample;

public interface XEmailConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    long countByExample(XEmailConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int deleteByExample(XEmailConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int insert(XEmailConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int insertSelective(XEmailConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    List<XEmailConfig> selectByExample(XEmailConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    XEmailConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int updateByExampleSelective(@Param("record") XEmailConfig record, @Param("example") XEmailConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int updateByExample(@Param("record") XEmailConfig record, @Param("example") XEmailConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int updateByPrimaryKeySelective(XEmailConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_email_config
     *
     * @mbg.generated Fri Apr 23 09:51:10 CST 2021
     */
    int updateByPrimaryKey(XEmailConfig record);
}