package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XJobMail;
import org.yaukie.frame.autocode.model.XJobMailExample;

public interface XJobMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    long countByExample(XJobMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int deleteByExample(XJobMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int insert(XJobMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int insertSelective(XJobMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    List<XJobMail> selectByExample(XJobMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    XJobMail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") XJobMail record, @Param("example") XJobMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int updateByExample(@Param("record") XJobMail record, @Param("example") XJobMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int updateByPrimaryKeySelective(XJobMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_job_mail
     *
     * @mbg.generated Fri Apr 23 11:14:22 CST 2021
     */
    int updateByPrimaryKey(XJobMail record);
}