package org.yaukie.frame.autocode.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yaukie.frame.autocode.model.XUser;
import org.yaukie.frame.autocode.model.XUserExample;

public interface XUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    long countByExample(XUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int deleteByExample(XUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int insert(XUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int insertSelective(XUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    List<XUser> selectByExample(XUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    XUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") XUser record, @Param("example") XUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int updateByExample(@Param("record") XUser record, @Param("example") XUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int updateByPrimaryKeySelective(XUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Apr 22 10:05:40 CST 2021
     */
    int updateByPrimaryKey(XUser record);

    /**
     * 根据条件获取用户列表
     * @param nickName
     * @param userPhone
     * @return
     */
    public List<XUser> getUserListByConditions(@Param("nickName")String nickName, @Param("userPhone")String userPhone);
}